apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: domain-ingress
spec:
  rules:
    - host: vm.adityajain2162.ksdns.io
      http:
        paths:
          - backend:
              serviceName: wisecow-service
              servicePort: 80
  tls:
    - hosts:
        - vm.adityajain2162.ksdns.io
      secretName: tls-secret
